services:
  minecraft-job:
    platform: linux/x86_64
    image: mysql
    container_name: minecraft-job-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./config/:/docker-entrypoint-initdb.d/
    ports:
      - 3307:3307