spring:
  mail:
    host: ${mail.host:smtp.gmail.com}
    port: 587
    default-encoding: utf-8
    username: ${mail.username:no.reply.mcj.server@gmail.com}
    password: ${mail.password:sabuvtjkselzygyh}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
