spring:
  mail:
    host: ${mail.host:smtp.gmail.com}
    port: 587
    default-encoding: utf-8
    username: ${MAIL_USER_NAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
