spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minecraft-job
    username: root
    password: ${password}
  flyway:
    enabled: true
    baseline-on-migrate: true
mybatis:
  type-aliases-package: spring.notice.springnotice
  mapper-locations: static/mapper/*.xml
