spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/minecraftjob
    username: root
    password: 1234
  flyway:
    enabled: false
    baseline-on-migrate: true
mybatis:
  type-aliases-package: spring.notice.springnotice
  mapper-locations: static/mapper/*.xml
