env:
  RESOURCE_PATH: ./api/src/main/resources/application.yml
  INTEGRATION_PATH: ./integration/src/main/resources/integration.yml
  S3_BUCKET_NAME: mcjserver
  CODE_DEPLOY_APPLICATION_NAME: title-code-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: title-server

name: CI

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, edited]
    
permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

        # [2]
      - name: Test with Gradle
        run: ./gradlew clean test
        shell: bash
