env:
  COMMON_TEST_RESOURCE_PATH: ./common/src/test/resources/application.yml
  API_TEST_RESOURCE_PATH: ./api/src/test/resources/application.yml
  RESOURCE_PATH: ./api/src/main/resources/application.yml
  INTEGRATION_PATH: ./integration/src/main/resources/integration.yml
  S3_BUCKET_NAME: mcjserver
  CODE_DEPLOY_APPLICATION_NAME: title-code-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: title-server

name: CI/CD

on:
  pull_request:
    branches: [ "main" ]
    types: 
      - closed

permissions:
  contents: read

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17


      - name: "application.yml Set"
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.RESOURCE_PATH }} 
        env:
          spring.datasource.url: ${{ secrets.RDB_URL }} 
          spring.datasource.username: ${{ secrets.RDB_USER_NAME }} 
          spring.datasource.password: ${{ secrets.RDB_PASSWORD }} 
          

      - name: "integration.yml Set"
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.INTEGRATION_PATH }} 
        env:
          spring.mail.username: ${{ secrets.MAIL_USER_NAME }} 
          spring.mail.password: ${{ secrets.MAIL_PASSWORD }} 

      - name: "COMMON Test application.yml Setting"
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.COMMON_TEST_RESOURCE_PATH }}
        env:
          spring.datasource.url: ${{ secrets.RDB_TEST_URL }}
          spring.datasource.username: ${{ secrets.RDB_USER_NAME }}
          spring.datasource.password: ${{ secrets.RDB_PASSWORD }}

      - name: "API Test application.yml Setting"
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.API_TEST_RESOURCE_PATH }}
        env:
          spring.datasource.url: ${{ secrets.RDB_TEST_URL }}
          spring.datasource.username: ${{ secrets.RDB_USER_NAME }}
          spring.datasource.password: ${{ secrets.RDB_PASSWORD }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: All Test with Gradle
        run: ./gradlew test
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean :api:buildNeeded --stacktrace --info -x test
        shell: bash

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ secrets.AWS_REGION }} 

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: | 
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
